services:
  claude:
    # Option 1: Pull image from Dockerhub
    image: skimming124/claude-code-docker
    # Option 2: Build image from source
    # build: .
    container_name: claude
    working_dir: /workspace
    volumes:
      # Replace `/absolute/path/to/your/projecty` with directory you want Claude Code to access
      - /absolute/path/to/your/project:/workspace
    tty: true
    stdin_open: true
    environment:
      - SHELL=/bin/bash
